app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
   path('vijay/',vijay,name='vijay'),
]

app2/urls.py
app_name='app2'
from django.urls import path
from app2.views import *

urlpatterns=[
    path('details/',details,name='details'),
]

project6/urls.py
from django.contrib import admin
from django.urls import path,include
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def vijay(request):
    return render(request,'vijay.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def details(request):
    return render(request,'details.html')

templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Vijay is a opener batsaman</h1>
        <h1>
            <a href="{% url 'app1:vijay' %}">click here</a>
        </h1>
    </center>
</body>
</html>

templates/vijay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Vijay is committed and waiting for marriage</h1>
        <h1>vijaysara reddy is grandfather</h1>
        <h1>
            <a href="{% url 'app2:details' %}">touch me</a>
        </h1>
    </center>
</body>
</html>